AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'my-artifact-bucket-${AWS::AccountId}-${AWS::Region}'

  MyCodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MyCodeCommitRepo
      RepositoryDescription: My CodeCommit Repository
      Tags:
        - Key: Name
          Value: MyCodeCommitRepo

  MyPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::my-artifact-bucket-${AWS::AccountId}-${AWS::Region}/*'
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - codecommit:*
                Resource: !GetAtt MyCodeCommitRepo.Arn
              - Effect: Allow
                Action:
                  - codedeploy:*
                Resource: '*'

  CFTRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: '*'

  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyPipeline
      RoleArn: !GetAtt MyPipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: MyCodeCommitRepo
                BranchName: main
              OutputArtifacts:
                - Name: SourceOutput
        - Name: DeployStage1
          Actions:
            - Name: DeployAction1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyStack1
                TemplatePath: SourceOutput::file1.yml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CFTRole.Arn
              InputArtifacts:
                - Name: SourceOutput
        - Name: DeployStage2
          Actions:
            - Name: DeployAction2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyStack2
                TemplatePath: SourceOutput::file2.yml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CFTRole.Arn
              InputArtifacts:
                - Name: SourceOutput
        - Name: DeployStage3
          Actions:
            - Name: DeployAction3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyStack3
                TemplatePath: SourceOutput::file3.yml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CFTRole.Arn
              InputArtifacts:
                - Name: SourceOutput
        - Name: DeployStage4
          Actions:
            - Name: DeployAction4
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyStack3
                TemplatePath: SourceOutput::file4.yml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CFTRole.Arn
              InputArtifacts:
                - Name: SourceOutput
